.TH STIG4DEBIAN 1 2017-08-16
.SH NAME
stig4debian \- DISA STIG for Debian 9 Porting from DISA RHEL 7 STIG V1 R1.
.SH SYNOPSIS
.B stig4debian 
.RB [ -s ]
.RB [ -v ]
.RB [ -h ]

.SH DESCRIPTION
usage: \fI\,/usr/bin/stig4debian\/\fP [options]
.TP
\fB\-s\fR
Start checking and output repot in html format.
.TP
\fB\-v\fR
Display version
.TP
\fB\-h\fR
Display help
.IP
Report is output in /var/log/stig4debian/STIG\-for\-Debian\-*.html
.PP
STIG for Debian Compliance Checking Tools (v2.0)
.PP
Ported from DISA RHEL 7 STIG
.PP

.SH AUTHOR
At was written by Samson Wen, sccxboy@gmail.com.

.SH NOTES
git address: https://github.com/harbian/stig4debian

